In [1]:
import pandas as pd

#Read Excel file and get insight
df12 = pd.read_excel('COOP4230_DS_PROJECT_DATA_12.xlsx', engine='openpyxl')
df12.head(5)

PeriodOrder                            CustomerId ValueBasedSegment  \
0           12  6B93AE32-CC94-4225-93A6-4B4E4FE3ED38                 X   
1           12  23F308B0-0A29-4FC7-A4BB-FFAB461643EC                 X   
2           12  14C523CD-12D8-435B-8BB3-10DB40C3EAA1                 X   
3           12  35B56EC7-903C-473A-883A-75CDD5F3F0B0                 X   
4           12  3A7D8BB6-5D84-4401-AF57-5BD58DFC1868                 X   

  ProfitSegment  YearlyIncome  AvgUsdAumL3M  AvgUsdAumL6M  SumUsdAum  \
0             D           0.0             0             0        0.0   
1             D         150.0           340           310      400.0   
2             D          10.0            10            10        0.0   
3             C         770.0             0             0        0.0   
4             B         850.0             0             0        0.0   

   MaxUsdAumL24M  AvgDemandDepositTrxUsdAmountL6M  ...  AvgBranchTrxNumL6M  \
0           50.0                                0  ...                0.28   
1          750.0                             1370  ...                   0   
2          140.0                             1040  ...                0.55   
3          790.0                              340  ...                   0   
4            0.0                              150  ...                   0   

   SumBranchTrxNumLM  SumCcIvrTrxNumL3M  SumCcIvrTrxNumL6M  \
0                NaN                  0                  0   
1                NaN                  0                  0   
2                NaN                  0                  0   
3                NaN                  0                  0   
4                NaN                  0                  0   

   SumDemandDepositTrxNumL3M  SumDemandDepositTrxNumL6M  \
0                        0.0                        0.0   
1                        2.0                        2.0   
2                        4.0                        8.0   
3                        6.0                        6.0   
4                        6.0                        6.0   

   BonusCampaignPromiseFlag  ClosedCreditCardFlag  ValidationFlag  ChurnFlag  
0                         0                     0               0        0.0  
1                         0                     0               0        0.0  
2                         0                     0               0        0.0  
3                         0                     0               0        0.0  
4                         0                     0               0        0.0  

[5 rows x 84 columns]

In [8]:
validation = df12.loc[df12['ValidationFlag'] == 1]

In [9]:
validation = validation.drop(['ChurnFlag', 'ValidationFlag'] , axis=1)

In [10]:
validation.head(10)

PeriodOrder                            CustomerId ValueBasedSegment  \
9            12  4238A086-DE09-441A-BBFC-579AAED7B561                 X   
14           12  B3EA8D2A-21BA-4083-8D27-B638B5B70954                 B   
15           12  0A98487E-6C9D-4C32-8C86-19A5A8C52F10                 X   
17           12  CFCBF9B9-E90F-4128-B864-8BDDA916F30E                 X   
22           12  1B33EA37-15E9-4AD3-90C3-2210F4BF665B                 X   
28           12  9754F08D-2194-4D0E-8EB0-8235EC75C98F                 X   
31           12  4F77F7BC-4704-4AB3-BEC2-8A9A7999AB70                 X   
35           12  DDDBFECA-A5A5-4E3B-8863-C96F8F50C87A                 X   
36           12  60102FA1-7C63-4BAD-91BB-23BB7573728D                 X   
43           12  80DBFA65-F431-4A84-B26A-8221766497D3                 X   

   ProfitSegment  YearlyIncome  AvgUsdAumL3M  AvgUsdAumL6M  SumUsdAum  \
9              D          90.0             0             0        0.0   
14             A       19290.0         45430         38200    48880.0   
15             D          20.0            10            10       10.0   
17             B        1400.0             0            10        0.0   
22             C         660.0             0             0        0.0   
28             D        -250.0           140            90      110.0   
31             D        -600.0            30            20       60.0   
35             D         220.0           430           320       10.0   
36             D         180.0             0             0        0.0   
43             D          10.0            20            20       20.0   

    MaxUsdAumL24M  AvgDemandDepositTrxUsdAmountL6M  ...  \
9            40.0                              800  ...   
14        48880.0                            15570  ...   
15           60.0                                0  ...   
17         1440.0                             2520  ...   
22           10.0                              220  ...   
28          220.0                             2940  ...   
31          610.0                             1210  ...   
35          780.0                             3360  ...   
36           80.0                                0  ...   
43           50.0                                0  ...   

    ClosedAutoBillPaymentOrderDurationMonthL12M  \
9                                             1   
14                                           -1   
15                                           -1   
17                                           -1   
22                                           -1   
28                                           -1   
31                                           -1   
35                                           -1   
36                                           -1   
43                                           -1   

    ClosedPayrollDurationMonthL12M   AvgBranchTrxNumL6M  SumBranchTrxNumLM  \
9                               -1                 0.28                NaN   
14                               1                    0                NaN   
15                              -1                    0                NaN   
17                              -1                    0                NaN   
22                              -1                 0.28                NaN   
28                              -1                    0                NaN   
31                              -1  1951-02-01 00:00:00                NaN   
35                              -1  1939-01-01 00:00:00                NaN   
36                              -1                    0                NaN   
43                               7                    0                NaN   

    SumCcIvrTrxNumL3M  SumCcIvrTrxNumL6M  SumDemandDepositTrxNumL3M  \
9                   2                  2                       10.0   
14                  0                  0                       12.0   
15                  0                  0                        6.0   
17                 

In [15]:
validation.isna().sum().sort_values(ascending=False).head(50)

SumClosedAutoBillPaymentOrderNumLM        11000
SumNewAutoBillPaymentOrderNumLM           10928
SumInboundTrxNumLM                        10890
SumFxDemandDepositTrxUsdAmountLM          10714
SumInboundNumLM                           10388
SumAutoBillPaymentNumLM                    9309
SumBranchTrxUsdAmountLM                    8947
SumBranchTrxNumLM                          8947
SumIncomingEftNumLM                        8658
SumEftNumLM                                8658
SumInstallmentLoanInstallmentBalanceLM     8519
SumInstallmentLoanOpeningBalanceUsdLM      8165
SumInstallmentLoanCurrentBalanceUsdLM      8165
AvgEftNumL3M                               7451
AvgCreditCardEftUsdAmountL3M               7451
MaxOverdraftBalanceUsdLM                   7433
AvgCreditCardEftUsdAmountL6M               6860
AvgEftNumL6M                               6860
CreditCardUsdLimitLM                       5026
SumCreditCardTrxUsdAmountLM                5026
SumCreditCardTrxNumLM                   

In [13]:
validation.shape

(11000, 82)

In [17]:
validation = validation.drop(["SumClosedAutoBillPaymentOrderNumLM",
"SumNewAutoBillPaymentOrderNumLM",
"SumInboundTrxNumLM"              ,               
"SumFxDemandDepositTrxUsdAmountLM" ,              
"SumInboundNumLM"                   ,             
"SumAutoBillPaymentNumLM",
"SumBranchTrxUsdAmountLM" ,                       
"SumBranchTrxNumLM"        ,                      
"SumIncomingEftNumLM"       ,                     
"SumEftNumLM"                ,                    
"SumInstallmentLoanInstallmentBalanceLM"         ,
"SumInstallmentLoanOpeningBalanceUsdLM"          ,
"SumInstallmentLoanCurrentBalanceUsdLM",
"MaxOverdraftBalanceUsdLM"              ,         
"AvgEftNumL3M"                           ,        
"AvgCreditCardEftUsdAmountL3M"            ,       
"AvgEftNumL6M"                             ,      
"AvgCreditCardEftUsdAmountL6M"              ,     
"CreditCardUsdLimitLM"                       ,    
"SumCreditCardRevolveUsdAmountLM"             ,   
"SumCreditCardTrxNumLM"                        ,  
"SumCreditCardTrxUsdAmountLM"                   , 
"SumAtmTrxUsdAmountLM"                           ,
"SumTrDemandDepositTrxUsdAmountLM"     ], axis=1)

In [18]:
validation.shape

(11000, 58)

Validation Null values after drop operation 

In [21]:
corr = validation.corr()
validation.isna().sum().sort_values(ascending=False).head(50)

SumDemandDepositTrxNumL6M                      718
SumDemandDepositTrxNumL3M                      601
SumLoanBalanceUsdLM                             13
YearlyIncome                                    13
SumUsdAum                                       13
MaxLoanBalanceL24M                               9
MaxUsdAumL24M                                    9
AvgDemandDepositTrxNumL6M                        0
AvgFxDemandDepositTrxNumL3M                      0
AvgFxDemandDepositTrxNumL6M                      0
AvgAtmTrxNumL6M                                  0
SumDemandDepositTrxTypeNumLM                     0
AvgInternetTrxNumL3M                             0
DemandDepositBalanceDebtRatioLM6                 0
AvgAutoBillPaymentNumLM6                         0
ActiveProductAndChannelGroupNum                  0
NewOpenProductAndChannelNumLM                    0
AvgInternetTrxNumL6M                             0
ClosedCreditCardFlag                             0
AvgInternetLoginNumL3M         

In [22]:
corr["SumDemandDepositTrxNumL3M"].sort_values(ascending=False).head(5)

SumDemandDepositTrxNumL3M          1.000000
SumDemandDepositTrxNumL6M          0.927083
SumDemandDepositTrxTypeNumLM       0.857341
ActiveProductAndChannelGroupNum    0.627571
Product13OwnershipFlag             0.566760
Name: SumDemandDepositTrxNumL3M, dtype: float64

In [24]:
nullIncomes = validation.loc[validation['SumLoanBalanceUsdLM'].isna()]
nullIncomes
validation = validation.drop(index= nullIncomes.index, axis= 0)

In [26]:
validation.isna().sum().sort_values(ascending=False).head(50)
nullIncomes = validation.loc[validation['YearlyIncome'].isna()]
validation = validation.drop(index= nullIncomes.index, axis= 0)

In [28]:
nullIncomes2 = validation.loc[validation['SumDemandDepositTrxNumL6M'].isna()] #validation dataset
print('Shape of current dfmodel' , validation.shape)
testDataframe = validation.drop(index= nullIncomes2.index, axis= 0)

nullIncomes3 = testDataframe.loc[validation['SumDemandDepositTrxNumL3M'].isna()]
testDataframe = testDataframe.drop(index= nullIncomes3.index, axis= 0)
print('Shape of testdataframe' , testDataframe.shape)

Shape of current dfmodel (10979, 58)
Shape of testdataframe (10135, 58)


In [29]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics
import numpy as np

values = testDataframe[['SumDemandDepositTrxNumL3M','SumDemandDepositTrxTypeNumLM' ]]
scaler = StandardScaler()
scaled = scaler.fit_transform(values)
inputs = pd.DataFrame(scaled)

target = testDataframe['SumDemandDepositTrxNumL6M']
target = target.to_numpy()
target = target.reshape(-1, 1)
print('real target')
print(target)
minxmaxScaler = MinMaxScaler()
newtarget = minxmaxScaler.fit_transform(target)
target = pd.DataFrame(newtarget)
print(target)


X_train, X_test, y_train, y_test = train_test_split( inputs, target, test_size=0.2, random_state=42)

regressor = LinearRegression()
regressor.fit(X_train, y_train)

#Test set
y_pred = regressor.predict(X_test)
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

#Real test
reversed_target2 = minxmaxScaler.inverse_transform(y_test)
print(reversed_target2)
reversed_target = minxmaxScaler.inverse_transform(y_pred)
print(reversed_target)

print('Mean Absolute Error:', metrics.mean_absolute_error(reversed_target2, reversed_target))
print('Mean Squared Error:', metrics.mean_squared_error(reversed_target2, reversed_target))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(reversed_target2, reversed_target)))

real target
[[16.]
 [14.]
 [ 8.]
 ...
 [ 0.]
 [ 6.]
 [ 6.]]
              0
0      0.444444
1      0.388889
2      0.222222
3      0.222222
4      0.000000
...         ...
10130  0.277778
10131  0.166667
10132  0.000000
10133  0.166667
10134  0.166667

[10135 rows x 1 columns]
Mean Absolute Error: 0.03874448153979775
Mean Squared Error: 0.0027087238309441695
Root Mean Squared Error: 0.05204540163111598
[[ 8.]
 [ 0.]
 [ 4.]
 ...
 [ 8.]
 [ 0.]
 [10.]]
[[9.40116402]
 [0.83588384]
 [5.02668763]
 ...
 [7.12208952]
 [0.83588384]
 [9.49300032]]
Mean Absolute Error: 1.3948013354327187
Mean Squared Error: 3.510506084903643
Root Mean Squared Error: 1.873634458720175


In [30]:
testDataframe.isna().sum().sort_values(ascending=False).head(5)

ClosedCreditCardFlag               0
AvgInternetLoginNumL3M             0
ClosedProductNumL3M                0
NewOpenProductAndChannelNumLM      0
ActiveProductAndChannelGroupNum    0
dtype: int64